In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [12]:
arr_1d = np.array([1,2,3,4,5])

In [15]:
arr_1d.shape

(5,)

In [14]:
type(arr_1d)

numpy.ndarray

In [17]:
arr_2d = np.array([[1,2,3],[4,5,6]])

In [18]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [33]:
arr_3d = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])


In [34]:
print(type(arr_3d))
print(arr_3d.ndim)

<class 'numpy.ndarray'>
3


In [ ]:
# np.zeros(shape) → all 0

# np.ones(shape) → all 1

# np.full(shape, value) → all same custom value

In [27]:
# one
one_np = np.ones([2,3])
print(one_np)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# zeros
one_np = np.zeros([2,3])
print(one_np)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# constant/full
one_np = np.full([2,3],555)
print(one_np)

[[555 555 555]
 [555 555 555]]


In [37]:
# identity matrix

I = np.eye(12,13)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [39]:
# range
r = np.arange(14)
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [44]:
r = np.arange(2,20,2)

In [45]:
r

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# np.linspace(start, stop, num)
# range = stop − start
# step = (stop − start) / (num − 1)

# linespace = equal space 
line_sp = np.linspace(0,15,3)

In [47]:
print(line_sp)

[ 0.   7.5 15. ]


In [50]:
array = np.array(([1,2,3],[4,5,6,]))
array.size

6

In [51]:
array.shape

(2, 3)

In [58]:
array_3d = np.array([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                      [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
print(array_3d)
print(array_3d.shape)
print(array_3d.ndim)
print(array_3d.size)
print(arr.dtype) 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(2, 3, 3)
3
18
float64


In [61]:
array_3d_float = array_3d.astype(float)
print(array_3d_float)
print(array_3d_float.dtype)


[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]

 [[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
float64


In [73]:
array_3d_float

array([[[  1., 100.,   3.],
        [  4., 100., 100.],
        [  7.,   8.,   9.]],

       [[  1.,   2.,   3.],
        [  4.,   5.,   6.],
        [  7.,   8.,   9.]]])

In [74]:
array_3d_float[0,0,1] = 100

In [75]:
print(array_3d_float)

[[[  1. 100.   3.]
  [  4. 100. 100.]
  [  7.   8.   9.]]

 [[  1.   2.   3.]
  [  4.   5.   6.]
  [  7.   8.   9.]]]


In [76]:
reshape = np.arange(6)

In [77]:
reshape.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [78]:
reshape.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [79]:
reshape.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [80]:
reshape.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [81]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])


In [ ]:
arr.flatten()  #flatten mean mutiple array convert into sible array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.T  # T mean transposer row ko col ma conver ya row ko col ma convert

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [84]:
arr[0]

array([1, 2, 3])

In [85]:
array[0][1]

np.int64(2)

In [90]:
arr = np.array([1,2,3,4,5,6,7,8,9])
boolean_arr = arr >= 6
print(boolean_arr)
print(arr[boolean_arr])

[False False False False False  True  True  True  True]
[6 7 8 9]


In [95]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:4])

[2 3 4]


In [97]:
print(arr[::2])

[1 3 5 7 9]


In [100]:
print(arr[::-2])

[9 7 5 3 1]


In [101]:
arr_2d = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
    )

In [102]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
arr_2d[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [105]:
arr_2d[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [107]:
# select alternate row
print(arr_2d[::2,:])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [109]:
print(arr_2d[::-1,:])

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [111]:
print(arr_2d[:,::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [112]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
arr3 = np.array([11, 12, 13, 14, 15])

In [113]:
sum = arr1 + arr2 + arr3

In [114]:
sum

array([18, 21, 24, 27, 30])

In [115]:
mul =arr1 * arr2 * arr3

In [116]:
mul

array([ 66, 168, 312, 504, 750])

In [117]:
Scal_mul = arr1 * 2

In [119]:
Scal_mul

array([ 2,  4,  6,  8, 10])

In [121]:
div = arr1 / arr2 / arr3
print(div)

[0.01515152 0.02380952 0.02884615 0.03174603 0.03333333]


In [122]:
print(np.min(arr_1d))

1


In [123]:
print(np.max(arr_1d))

5


In [124]:
print(np.average(arr_1d))

3.0


In [125]:
print(np.mean(arr_1d))

3.0


In [127]:
# square
print(np.square(arr1))

[ 1  4  9 16 25]


In [128]:
# expotential
print(np.exp(arr1))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [129]:
# sum
print(np.sum(arr1))

15


In [130]:
print(np.mean(arr1))

3.0


In [131]:
print(np.std(arr1))

1.4142135623730951


In [133]:
print(np.var(arr1))

2.0


In [142]:
import numpy as np

# 1. Append in NumPy
# np.append() is used to add values to an array.
# It creates a new array with the added elements.

arr = np.array([1, 2, 4])
# new = np.append(arr, [7, 8])
# print(new)

# Multi-Dimensional Example

# append row
# arr = np.array([[1, 2], [4, 5]])
# new = np.append(arr, [[7, 8]], axis = 0)
# print(new)

# Append a new column [[5], [6]]
# arr = np.array([[1, 2], [4, 5]])
# new = np.append(arr,[[7],[9]],axis=1)
# print(new)

# 2. Concatenate Arrays
# np.concatenate() joins arrays along existing axis.
# 2D Example - Along Rows (axis=0)
x = np.array([[1, 2], [3, 4]])
# y = np.array([[8, 9]])
# res = np.concatenate((x, y), axis=0)
# print(res)

# Concatenate Along Columns (axis=1)
# Note: Dono arrays mein number of rows (2) same honi chahiye
y_col = np.array([[8], [9]])
res_col = np.concatenate((x, y_col), axis=1)
print(res_col)

[[1 2 8]
 [3 4 9]]


In [146]:
# --- 3. Insert Elements ---
# np.insert() inserts values at a specified position/index.
# Syntax: np.insert(array, index, values)

# Example:
a = np.array([1, 2, 3])
np.insert(a, 1, [15,8])

array([ 1, 15,  8,  2,  3])